name: NDK build

on:
  workflow_dispatch:
  push:
    branches: [master, qpm-rust]
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/build-ndk.yml'
      - '**.json'
      - '!qpm.json'
      - '!mod.template.json'
      - '**.txt'
      - '!CMakeLists.txt'
      - '**.ps1'
      - '!build.ps1'
      - '!createqmod.ps1'
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: master

env:
    module_id: qosmetics-core
    qmodName: QosmeticsCore

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true
    
    - uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Create ndkpath.txt
      run: |
        echo "$ANDROID_NDK_LATEST_HOME" > ${GITHUB_WORKSPACE}/ndkpath.txt
        cat ${GITHUB_WORKSPACE}/ndkpath.txt

    - name: Get QPM
      if: steps.cache-qpm.outputs.cache-hit != 'true'
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: cargo-build.yml
        name: linux-qpm-rust
        path: QPM
        repo: RedBrumbler/QuestPackageManager-Rust
        
    - name: QPM Collapse
      run: |
        chmod +x ./QPM/qpm-rust
        ./QPM/qpm-rust collapse
    
    - name: QPM Dependencies Cache
      id: cache-qpm-deps
      uses: actions/cache@v2
      env:
        cache-name: cache-qpm-deps
      with:
        path: /home/runner/.local/share/QPM-Rust/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('qpm.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: QPM Restore
      run: |
        ./QPM/qpm-rust restore
        
    - name: Run QPM legacy fix
      run: ./QPM/qpm-rust cache legacy-fix

    - name: List Post Restore
      run: |
        echo includes:
        ls -la ${GITHUB_WORKSPACE}/extern/includes
        echo libs:
        ls -la ${GITHUB_WORKSPACE}/extern/libs
        echo cache:
        ls -la $HOME/.local/share/QPM-Rust/cache
      
    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}
        ./QPM/qpm-rust qmod build --include_libs lib${module_id}.so libcustom-types.so libbeatsaber-hook_2_3_2.so libbs-utils.so
        pwsh -Command ./build.ps1

    - name: Create Qmod
      run: |
        pwsh -Command ./createqmod.ps1 ${{env.qmodName}}

    - name: Get Library Name
      id: libname
      run: |
        cd ./build/
        pattern="lib${module_id}*.so"
        files=( $pattern )
        echo ::set-output name=NAME::"${files[0]}"
    
#    - name: Upload non-debug artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{ steps.libname.outputs.NAME }}
#        path: ./build/${{ steps.libname.outputs.NAME }}
#        if-no-files-found: error
#
#    - name: Upload debug artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: debug_${{ steps.libname.outputs.NAME }}
#        path: ./build/debug_${{ steps.libname.outputs.NAME }}
#        if-no-files-found: error
#
#    - name: Upload qmod artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{env.qmodName}}.qmod
#        path: ./${{ env.qmodName }}.qmod
#        if-no-files-found: error

    - name: Check if webhook secret set
      id: webhook-set
      run: echo ::set-output name=EXISTS::"${{secrets.DISCORD_WEBHOOK_URL != ''}}"

    - name: Publish release.so to webhook
      if: ${{ steps.webhook-set.outputs.EXISTS }}
      uses: tsickert/discord-webhook@v3.2.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "${{ env.CI_SHA_SHORT }} - `${{ github.event.head_commit.message }}`\nrelease.so"
        username: "${{ github.repository }}"
        avatar-url: "http://github.com/${{ env.CI_REPOSITORY_OWNER }}.png"
        filename: ./build/${{ steps.libname.outputs.NAME }}

    - name: Publish debug.so to webhook
      if: ${{ steps.webhook-set.outputs.EXISTS }}
      uses: tsickert/discord-webhook@v3.2.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "debug.so"
        username: "${{ github.repository }}"
        avatar-url: "http://github.com/${{ env.CI_REPOSITORY_OWNER }}.png"
        filename: ./build/debug_${{ steps.libname.outputs.NAME }}

    - name: Publish qmod to webhook
      uses: tsickert/discord-webhook@v3.2.0
      with:
        # Url is github secret, so it doesn't get leaked
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        # last commit message will be the given text
        content: "qmod"
        # user is repo name
        username: "${{ github.repository }}"
        # avatar url is repo owner avatar
        avatar-url: "http://github.com/${{ env.CI_REPOSITORY_OWNER }}.png"
        # file to upload is the qmod
        filename: ./${{ env.qmodName }}.qmod
       # Disabling qmod upload becasue people are getting qmods from GH actions when they should not
#    - name: Upload qmod artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: ${{ env.qmodName }}.qmod
#        path: ./${{ env.qmodName }}.qmod
#        # if not found error obviously
#        if-no-files-found: error

    # TODO: Add auto-populating releases, auto update versions, auto publish package on release
